### ISSUE TITLE
Add github workflows

### ISSUE THREAD

**Issue by abianche** [abianche/firstday#1]
Sample

```yaml

name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
         channel: stable
         cache: true
      - run: flutter --version

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Analyze the code
      - name: Run Flutter Analyze
        run: flutter analyze

      # Run Tests
      - name: Run Tests
        run: flutter test
```
